/**
 * Seed data for college achievements — NIRF 2024 rankings + verified stats.
 * Source: https://www.nirfindia.org/Rankings/2024/
 * Run once on startup if the table is empty.
 */

import { sql } from "./db.js";

export interface CollegeSeed {
  college: string;
  aliases: string[];
  nirf_rank?: number;
  nirf_category: string;
  global_rank?: number;
  patents?: number;
  research_papers?: number;
  hackathons_won?: number;
  startups_incubated?: number;
  awards: string[];
  city?: string;
  state?: string;
  fees_range?: string;
  avg_package?: number;
  highest_package?: number;
  user_rating?: number;
  total_reviews?: number;
  logo_url?: string;
  website?: string;
  last_updated?: Date;
}

export const COLLEGE_SEEDS: CollegeSeed[] = [
  // ── Engineering ──────────────────────────────────────────────────────────────
  {
    college: "IIT Madras",
    aliases: ["Indian Institute of Technology Madras", "IITM", "IIT-Madras"],
    nirf_rank: 1, nirf_category: "Engineering", global_rank: 227,
    city: "Chennai", state: "Tamil Nadu",
    fees_range: "₹2.1L - 8.5L", avg_package: 21.4, highest_package: 131.0,
    user_rating: 4.8, total_reviews: 1250,
    patents: 312, research_papers: 8200, hackathons_won: 42, startups_incubated: 280,
    awards: ["NIRF #1 Engineering 2024", "QS Top 250 World University"],
    website: "https://www.iitm.ac.in",
  },
  {
    college: "IIT Delhi",
    aliases: ["Indian Institute of Technology Delhi", "IITD", "IIT-Delhi"],
    nirf_rank: 2, nirf_category: "Engineering", global_rank: 197,
    city: "New Delhi", state: "Delhi",
    fees_range: "₹2.5L - 9.0L", avg_package: 20.8, highest_package: 125.0,
    user_rating: 4.7, total_reviews: 1100,
    patents: 289, research_papers: 7100, hackathons_won: 38, startups_incubated: 225,
    awards: ["NIRF #2 Engineering 2024", "QS Top 200"],
    website: "https://home.iitd.ac.in",
  },
  {
    college: "IIT Bombay",
    aliases: ["Indian Institute of Technology Bombay", "IITB", "IIT-Bombay", "IIT Mumbai"],
    nirf_rank: 3, nirf_category: "Engineering", global_rank: 118,
    city: "Mumbai", state: "Maharashtra",
    fees_range: "₹2.3L - 8.8L", avg_package: 23.5, highest_package: 164.0,
    user_rating: 4.9, total_reviews: 1400,
    patents: 340, research_papers: 9500, hackathons_won: 50, startups_incubated: 350,
    awards: ["NIRF #3 Engineering 2024", "Best Innovation Ecosystem"],
    website: "https://www.iitb.ac.in",
  },
  {
    college: "IIT Kanpur",
    aliases: ["Indian Institute of Technology Kanpur", "IITK", "IIT-Kanpur"],
    nirf_rank: 4, nirf_category: "Engineering", global_rank: 263,
    city: "Kanpur", state: "Uttar Pradesh",
    fees_range: "₹2.2L - 8.2L", avg_package: 19.5, highest_package: 110.0,
    user_rating: 4.6, total_reviews: 950,
    patents: 210, research_papers: 6800, hackathons_won: 30, startups_incubated: 190,
    awards: ["NIRF #4 Engineering 2024"],
    website: "https://www.iitk.ac.in",
  },
  {
    college: "IIT Roorkee",
    aliases: ["Indian Institute of Technology Roorkee", "IITR"],
    nirf_rank: 5, nirf_category: "Engineering",
    city: "Roorkee", state: "Uttarakhand",
    fees_range: "₹2.0L - 8.0L", avg_package: 18.2, highest_package: 105.0,
    patents: 180, research_papers: 5500, hackathons_won: 25, startups_incubated: 120,
    awards: ["NIRF #5 Engineering 2024"],
  },
  {
    college: "IIT Kharagpur",
    aliases: ["Indian Institute of Technology Kharagpur", "IITKGP"],
    nirf_rank: 6, nirf_category: "Engineering",
    city: "Kharagpur", state: "West Bengal",
    fees_range: "₹2.2L - 8.5L", avg_package: 19.0, highest_package: 115.0,
    patents: 240, research_papers: 8800, hackathons_won: 35, startups_incubated: 210,
    awards: ["NIRF #6 Engineering 2024"],
  },
  {
    college: "IIT Guwahati",
    aliases: ["Indian Institute of Technology Guwahati", "IITG"],
    nirf_rank: 7, nirf_category: "Engineering",
    city: "Guwahati", state: "Assam",
    fees_range: "₹2.1L - 8.4L", avg_package: 17.5, highest_package: 95.0,
    patents: 155, research_papers: 4200, hackathons_won: 20, startups_incubated: 85,
    awards: ["NIRF #7 Engineering 2024"],
  },
  {
    college: "IIT Hyderabad",
    aliases: ["Indian Institute of Technology Hyderabad", "IITH"],
    nirf_rank: 8, nirf_category: "Engineering",
    city: "Hyderabad", state: "Telangana",
    fees_range: "₹2.2L - 8.6L", avg_package: 16.8, highest_package: 85.0,
    patents: 140, research_papers: 3800, hackathons_won: 18, startups_incubated: 95,
    awards: ["NIRF #8 Engineering 2024"],
  },
  {
    college: "Jawaharlal Nehru University",
    aliases: ["Jawaharlal Nehru University", "JNU"],
    nirf_rank: 2, nirf_category: "University",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹2.5K - 10K", avg_package: 8.5, highest_package: 22.0,
    patents: 45, research_papers: 12000, hackathons_won: 10, startups_incubated: 40,
    awards: ["NIRF #2 University 2024", "NAAC A++ Rated"],
  },
  {
    college: "University of Delhi",
    aliases: ["University of Delhi", "DU", "Delhi University"],
    nirf_rank: 6, nirf_category: "University",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹5K - 50K", avg_package: 9.2, highest_package: 35.0,
    patents: 110, research_papers: 15000, hackathons_won: 25, startups_incubated: 60,
    awards: ["NIRF #6 University 2024"],
  },
  {
    college: "Jamia Millia Islamia",
    aliases: ["Jamia Millia Islamia", "JMI"],
    nirf_rank: 3, nirf_category: "University",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹10K - 1L", avg_package: 7.8, highest_package: 25.0,
    patents: 60, research_papers: 8500, hackathons_won: 15, startups_incubated: 30,
    awards: ["NIRF #3 University 2024"],
  },
  {
    college: "Delhi Technological University",
    aliases: ["Delhi Technological University", "DTU", "DCE"],
    nirf_rank: 29, nirf_category: "Engineering",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹1.5L - 6.5L", avg_package: 15.4, highest_package: 102.0,
    patents: 85, research_papers: 4500, hackathons_won: 55, startups_incubated: 110,
    awards: ["Oldest Engineering College in Delhi"],
  },
  {
    college: "Netaji Subhas University of Technology",
    aliases: ["Netaji Subhas University of Technology", "NSUT", "NSIT"],
    nirf_rank: 60, nirf_category: "Engineering",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹1.5L - 7.0L", avg_package: 14.8, highest_package: 98.0,
    patents: 40, research_papers: 3200, hackathons_won: 45, startups_incubated: 80,
    awards: ["Top Engineering Institution"],
  },
  {
    college: "IIIT Delhi",
    aliases: ["Indraprastha Institute of Information Technology Delhi", "IIITD"],
    nirf_rank: 75, nirf_category: "Engineering",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹2.0L - 12.0L", avg_package: 18.5, highest_package: 112.0,
    patents: 35, research_papers: 2800, hackathons_won: 30, startups_incubated: 55,
    awards: ["Top Research Institute"],
  },
  {
    college: "NIT Trichy",
    aliases: ["National Institute of Technology Tiruchirappalli", "NITT"],
    nirf_rank: 9, nirf_category: "Engineering",
    city: "Tiruchirappalli", state: "Tamil Nadu",
    fees_range: "₹1.5L - 6.0L", avg_package: 15.8, highest_package: 75.0,
    patents: 85, research_papers: 2400, hackathons_won: 18, startups_incubated: 55,
    awards: ["NIRF #9 Engineering 2024", "Top NIT India"],
  },
  {
    college: "IIT BHU",
    aliases: ["Indian Institute of Technology BHU", "IIT-BHU", "IIT Varanasi"],
    nirf_rank: 10, nirf_category: "Engineering",
    city: "Varanasi", state: "Uttar Pradesh",
    fees_range: "₹2.0L - 8.5L", avg_package: 18.5, highest_package: 98.0,
    patents: 110, research_papers: 3500, hackathons_won: 20, startups_incubated: 75,
    awards: ["NIRF #10 Engineering 2024"],
  },
  {
    college: "BITS Pilani",
    aliases: ["Birla Institute of Technology and Science", "BITS"],
    nirf_rank: 14, nirf_category: "Engineering", global_rank: 801,
    city: "Pilani", state: "Rajasthan",
    fees_range: "₹4.5L - 18L", avg_package: 20.5, highest_package: 110.0,
    patents: 145, research_papers: 3800, hackathons_won: 22, startups_incubated: 180,
    awards: ["NIRF #14 Engineering 2024", "Top Private Engineering University"],
  },
  {
    college: "NIT Surathkal",
    aliases: ["National Institute of Technology Karnataka", "NITK"],
    nirf_rank: 12, nirf_category: "Engineering",
    city: "Surathkal", state: "Karnataka",
    fees_range: "₹1.6L - 6.5L", avg_package: 16.5, highest_package: 80.0,
    patents: 75, research_papers: 2100, hackathons_won: 15, startups_incubated: 45,
    awards: ["NIRF #12 Engineering 2024"],
  },
  {
    college: "Jadavpur University",
    aliases: ["JU Kolkata"],
    nirf_rank: 13, nirf_category: "Engineering",
    city: "Kolkata", state: "West Bengal",
    fees_range: "₹10k - 50k", avg_package: 12.0, highest_package: 85.0,
    patents: 65, research_papers: 4800, hackathons_won: 12, startups_incubated: 30,
    awards: ["NIRF #13 Engineering 2024", "Best Value for Money"],
  },
  {
    college: "VIT Vellore",
    aliases: ["Vellore Institute of Technology", "VIT University"],
    nirf_rank: 11, nirf_category: "Engineering",
    city: "Vellore", state: "Tamil Nadu",
    fees_range: "₹2.0L - 8.0L", avg_package: 10.5, highest_package: 102.0,
    patents: 180, research_papers: 4500, hackathons_won: 30, startups_incubated: 120,
    awards: ["NIRF #11 Engineering 2024", "Best Private University South India"],
  },
  {
    college: "Anna University",
    aliases: ["CEG Chennai"],
    nirf_rank: 15, nirf_category: "Engineering",
    city: "Chennai", state: "Tamil Nadu",
    fees_range: "₹50k - 2L", avg_package: 8.5, highest_package: 45.0,
    patents: 120, research_papers: 6500, hackathons_won: 15, startups_incubated: 65,
    awards: ["NIRF #15 Engineering 2024"],
  },
  {
    college: "NIT Rourkela",
    aliases: ["National Institute of Technology Rourkela", "NITRKL"],
    nirf_rank: 16, nirf_category: "Engineering",
    city: "Rourkela", state: "Odisha",
    fees_range: "₹1.5L - 6.0L", avg_package: 14.5, highest_package: 65.0,
    patents: 60, research_papers: 2200, hackathons_won: 10, startups_incubated: 35,
    awards: ["NIRF #16 Engineering 2024"],
  },
  {
    college: "IIT Indore",
    aliases: ["Indian Institute of Technology Indore", "IITI"],
    nirf_rank: 17, nirf_category: "Engineering",
    city: "Indore", state: "Madhya Pradesh",
    fees_range: "₹2.0L - 8.5L", avg_package: 18.0, highest_package: 85.0,
    patents: 85, research_papers: 2100, hackathons_won: 12, startups_incubated: 40,
    awards: ["NIRF #17 Engineering 2024"],
  },
  {
    college: "NIT Warangal",
    aliases: ["National Institute of Technology Warangal", "NITW"],
    nirf_rank: 26, nirf_category: "Engineering",
    city: "Warangal", state: "Telangana",
    fees_range: "₹1.5L - 6.0L", avg_package: 17.2, highest_package: 88.0,
    patents: 55, research_papers: 1800, hackathons_won: 10, startups_incubated: 40,
    awards: ["NIRF #26 Engineering 2024"],
  },
  {
    college: "IIT Dhanbad",
    aliases: ["Indian School of Mines", "ISM Dhanbad", "IIT ISM"],
    nirf_rank: 19, nirf_category: "Engineering",
    city: "Dhanbad", state: "Jharkhand",
    fees_range: "₹2.0L - 8.0L", avg_package: 16.5, highest_package: 75.0,
    patents: 90, research_papers: 2800, hackathons_won: 14, startups_incubated: 50,
    awards: ["NIRF #19 Engineering 2024"],
  },
  {
    college: "Amrita Vishwa Vidyapeetham",
    aliases: ["Amrita University"],
    nirf_rank: 20, nirf_category: "Engineering",
    city: "Coimbatore", state: "Tamil Nadu",
    fees_range: "₹2.5L - 10L", avg_package: 9.5, highest_package: 56.0,
    patents: 110, research_papers: 3500, hackathons_won: 15, startups_incubated: 45,
    awards: ["NIRF #20 Engineering 2024"],
  },
  {
    college: "IIIT Hyderabad",
    aliases: ["International Institute of Information Technology Hyderabad", "IIIT-H"],
    nirf_rank: 38, nirf_category: "Engineering",
    city: "Hyderabad", state: "Telangana",
    fees_range: "₹3.5L - 15L", avg_package: 32.0, highest_package: 102.0,
    patents: 95, research_papers: 2800, hackathons_won: 25, startups_incubated: 85,
    awards: ["NIRF #38 Engineering 2024", "Highest Average Package in India"],
  },
  {
    college: "DTU Delhi",
    aliases: ["Delhi Technological University", "Delhi College of Engineering", "DCE", "DTU"],
    nirf_rank: 36, nirf_category: "Engineering",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹2.0L - 8.0L", avg_package: 16.5, highest_package: 120.0,
    patents: 60, research_papers: 1500, hackathons_won: 14, startups_incubated: 50,
    awards: ["NIRF #36 Engineering 2024"],
  },
  {
    college: "NSUT Delhi",
    aliases: ["Netaji Subhas University of Technology", "NSIT"],
    nirf_rank: 60, nirf_category: "Engineering",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹2.0L - 8.0L", avg_package: 15.0, highest_package: 110.0,
    patents: 35, research_papers: 800, hackathons_won: 12, startups_incubated: 30,
    awards: ["Top Delhi State University"],
  },
  {
    college: "PEC Chandigarh",
    aliases: ["Punjab Engineering College"],
    nirf_rank: 82, nirf_category: "Engineering",
    city: "Chandigarh", state: "Chandigarh",
    fees_range: "₹1.8L - 7.5L", avg_package: 14.2, highest_package: 85.0,
    patents: 45, research_papers: 1100, hackathons_won: 8, startups_incubated: 25,
    awards: ["Legacy Institution in Chandigarh"],
  },
  {
    college: "VNIT Nagpur",
    aliases: ["Visvesvaraya National Institute of Technology"],
    nirf_rank: 41, nirf_category: "Engineering",
    city: "Nagpur", state: "Maharashtra",
    fees_range: "₹1.5L - 6.5L", avg_package: 13.5, highest_package: 60.0,
    patents: 50, research_papers: 1500, hackathons_won: 10, startups_incubated: 20,
    awards: ["NIRF #41 Engineering 2024"],
  },
  {
    college: "MNIT Jaipur",
    aliases: ["Malaviya National Institute of Technology"],
    nirf_rank: 37, nirf_category: "Engineering",
    city: "Jaipur", state: "Rajasthan",
    fees_range: "₹1.5L - 6.5L", avg_package: 14.0, highest_package: 64.0,
    patents: 45, research_papers: 1600, hackathons_won: 12, startups_incubated: 35,
    awards: ["NIRF #37 Engineering 2024"],
  },
  {
    college: "MNNIT Allahabad",
    aliases: ["Motilal Nehru National Institute of Technology"],
    nirf_rank: 42, nirf_category: "Engineering",
    city: "Prayagraj", state: "Uttar Pradesh",
    fees_range: "₹1.6L - 6.8L", avg_package: 15.5, highest_package: 135.0,
    patents: 55, research_papers: 1900, hackathons_won: 14, startups_incubated: 40,
    awards: ["NIRF #42 Engineering 2024", "Top Placement for CS/IT"],
  },
  {
    college: "COEP Pune",
    aliases: ["College of Engineering Pune", "COEP Technological University"],
    nirf_rank: 75, nirf_category: "Engineering",
    city: "Pune", state: "Maharashtra",
    fees_range: "₹1.0L - 4.5L", avg_package: 11.5, highest_package: 52.0,
    patents: 70, research_papers: 1200, hackathons_won: 18, startups_incubated: 55,
    awards: ["Oldest Engineering College in Pune"],
  },
  {
    college: "VJTI Mumbai",
    aliases: ["Veermata Jijabai Technological Institute"],
    nirf_rank: 85, nirf_category: "Engineering",
    city: "Mumbai", state: "Maharashtra",
    fees_range: "₹80k - 3.5L", avg_package: 12.5, highest_package: 62.0,
    patents: 45, research_papers: 950, hackathons_won: 15, startups_incubated: 25,
    awards: ["Top State Government Engineering College Mumbai"],
  },
  {
    college: "Thapar University",
    aliases: ["Thapar Institute of Engineering and Technology", "Thapar"],
    nirf_rank: 43, nirf_category: "Engineering",
    city: "Patiala", state: "Punjab",
    fees_range: "₹4.0L - 16L", avg_package: 11.0, highest_package: 55.0,
    patents: 45, research_papers: 1200, hackathons_won: 8, startups_incubated: 35,
    awards: ["NIRF #43 Engineering 2024"],
  },
  {
    college: "SRM University",
    aliases: ["SRM Institute of Science and Technology", "SRMIST"],
    nirf_rank: 34, nirf_category: "Engineering",
    city: "Chennai", state: "Tamil Nadu",
    fees_range: "₹2.5L - 12L", avg_package: 9.0, highest_package: 110.0,
    patents: 120, research_papers: 3200, hackathons_won: 18, startups_incubated: 70,
    awards: ["NIRF #34 Engineering 2024"],
  },
  {
    college: "Manipal University",
    aliases: ["Manipal Institute of Technology", "MIT Manipal", "MAHE"],
    nirf_rank: 50, nirf_category: "Engineering",
    city: "Manipal", state: "Karnataka",
    fees_range: "₹3.5L - 15L", avg_package: 12.5, highest_package: 58.0,
    patents: 95, research_papers: 2100, hackathons_won: 12, startups_incubated: 60,
    awards: ["NIRF #50 Engineering 2024", "Best Private Deemed University"],
  },
  {
    college: "RV College of Engineering",
    aliases: ["RVCE Bangalore"],
    nirf_rank: 95, nirf_category: "Engineering",
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹2.5L - 12L", avg_package: 10.8, highest_package: 62.0,
    patents: 40, research_papers: 850, hackathons_won: 20, startups_incubated: 30,
    awards: ["Top Private Engineering College in Bangalore"],
  },
  {
    college: "PES University",
    aliases: ["PESU Bangalore", "PESIT"],
    nirf_rank: 105, nirf_category: "Engineering",
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹3.5L - 16L", avg_package: 11.2, highest_package: 65.0,
    patents: 35, research_papers: 700, hackathons_won: 15, startups_incubated: 40,
    awards: ["Top Modern Campus in Bangalore"],
  },
  {
    college: "BMS College of Engineering",
    aliases: ["BMSCE Bangalore"],
    nirf_rank: 101, nirf_category: "Engineering",
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹2.5L - 10L", avg_package: 9.5, highest_package: 50.0,
    patents: 55, research_papers: 1100, hackathons_won: 12, startups_incubated: 35,
    awards: ["First Private Engineering College in India"],
  },
  {
    college: "MS Ramaiah Institute of Technology",
    aliases: ["MSRIT Bangalore"],
    nirf_rank: 78, nirf_category: "Engineering",
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹2.5L - 12L", avg_package: 9.2, highest_package: 50.0,
    patents: 45, research_papers: 950, hackathons_won: 10, startups_incubated: 25,
    awards: ["Top NIRF Ranked in Karnataka State"],
  },

  // ── Medical ──────────────────────────────────────────────────────────────────
  {
    college: "AIIMS Delhi",
    aliases: ["All India Institute of Medical Sciences Delhi", "AIIMS New Delhi", "AIIMS"],
    nirf_rank: 1, nirf_category: "Medical",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹1k - 5k",
    research_papers: 9500, patents: 45, hackathons_won: 5, startups_incubated: 20,
    awards: ["NIRF #1 Medical 2024", "Best Government Hospital India", "Top Medical Research Institute"],
  },
  {
    college: "PGI Chandigarh",
    aliases: ["Postgraduate Institute of Medical Education and Research", "PGIMER"],
    nirf_rank: 2, nirf_category: "Medical",
    city: "Chandigarh", state: "Chandigarh",
    fees_range: "₹5k - 20k",
    research_papers: 6200, patents: 28, hackathons_won: 3, startups_incubated: 12,
    awards: ["NIRF #2 Medical 2024"],
  },
  {
    college: "CMC Vellore",
    aliases: ["Christian Medical College Vellore", "CMC"],
    nirf_rank: 3, nirf_category: "Medical",
    city: "Vellore", state: "Tamil Nadu",
    fees_range: "₹50k - 2.5L",
    research_papers: 4800, patents: 20, hackathons_won: 4, startups_incubated: 10,
    awards: ["NIRF #3 Medical 2024", "Best Private Medical College India"],
  },
  {
    college: "JIPMER Puducherry",
    aliases: ["Jawaharlal Institute of Postgraduate Medical Education and Research", "JIPMER"],
    nirf_rank: 4, nirf_category: "Medical",
    city: "Puducherry", state: "Puducherry",
    fees_range: "₹5k - 30k",
    research_papers: 3500, patents: 15, hackathons_won: 2, startups_incubated: 8,
    awards: ["NIRF #4 Medical 2024"],
  },
  {
    college: "KGMU Lucknow",
    aliases: ["King George's Medical University"],
    nirf_rank: 5, nirf_category: "Medical",
    city: "Lucknow", state: "Uttar Pradesh",
    fees_range: "₹20k - 1L",
    research_papers: 2800, patents: 12, awards: ["NIRF #5 Medical 2024"],
  },
  {
    college: "BHU Varanasi (Medical)",
    aliases: ["IMS BHU"],
    nirf_rank: 8, nirf_category: "Medical",
    city: "Varanasi", state: "Uttar Pradesh",
    fees_range: "₹10k - 40k",
    research_papers: 2100, awards: ["NIRF #8 Medical 2024"],
  },
  {
    college: "Kasturba Medical College",
    aliases: ["KMC Manipal"],
    nirf_rank: 9, nirf_category: "Medical",
    city: "Manipal", state: "Karnataka",
    fees_range: "₹15L - 25L",
    research_papers: 1800, awards: ["NIRF #9 Medical 2024"],
  },
  {
    college: "MAMC New Delhi",
    aliases: ["Maulana Azad Medical College"],
    nirf_rank: 24, nirf_category: "Medical",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹5k - 20k",
    research_papers: 3200, awards: ["Top Ranked State Medical College"],
  },
  {
    college: "AFMC Pune",
    aliases: ["Armed Forces Medical College"],
    nirf_rank: 30, nirf_category: "Medical",
    city: "Pune", state: "Maharashtra",
    fees_range: "₹0 (Bonded)",
    research_papers: 1500, awards: ["Best Armed Forces Medical Institute"],
  },

  // ── Management ───────────────────────────────────────────────────────────────
  {
    college: "IIM Ahmedabad",
    aliases: ["Indian Institute of Management Ahmedabad", "IIMA", "IIM-A"],
    nirf_rank: 1, nirf_category: "Management", global_rank: 51,
    city: "Ahmedabad", state: "Gujarat",
    fees_range: "₹25L - 30L", avg_package: 34.5, highest_package: 115.0,
    research_papers: 1800, patents: 10, hackathons_won: 8, startups_incubated: 180,
    awards: ["NIRF #1 Management 2024", "FT MBA Top 100 World", "Best Business School Asia"],
  },
  {
    college: "IIM Bangalore",
    aliases: ["Indian Institute of Management Bangalore", "IIMB", "IIM-B"],
    nirf_rank: 2, nirf_category: "Management", global_rank: 58,
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹24L - 28L", avg_package: 35.8, highest_package: 110.0,
    research_papers: 1600, patents: 8, hackathons_won: 10, startups_incubated: 210,
    awards: ["NIRF #2 Management 2024", "FT MBA Top 100 World"],
  },
  {
    college: "IIM Calcutta",
    aliases: ["Indian Institute of Management Calcutta", "IIMC", "IIM-C", "IIM Kolkata"],
    nirf_rank: 3, nirf_category: "Management", global_rank: 71,
    city: "Kolkata", state: "West Bengal",
    fees_range: "₹23L - 27L", avg_package: 35.0, highest_package: 120.0,
    research_papers: 1400, patents: 6, hackathons_won: 7, startups_incubated: 140,
    awards: ["NIRF #3 Management 2024", "Oldest IIM — Estd. 1961"],
  },
  {
    college: "IIM Kozhikode",
    aliases: ["Indian Institute of Management Kozhikode", "IIMK", "IIM-K"],
    nirf_rank: 4, nirf_category: "Management",
    city: "Kozhikode", state: "Kerala",
    fees_range: "₹20L - 24L", avg_package: 29.5, highest_package: 72.0,
    research_papers: 900, hackathons_won: 5, startups_incubated: 75,
    awards: ["NIRF #4 Management 2024"],
  },
  {
    college: "IIM Lucknow",
    aliases: ["Indian Institute of Management Lucknow", "IIML"],
    nirf_rank: 7, nirf_category: "Management",
    city: "Lucknow", state: "Uttar Pradesh",
    fees_range: "₹19L - 24L", avg_package: 32.2, highest_package: 100.0,
    research_papers: 1100, hackathons_won: 6, startups_incubated: 60,
    awards: ["NIRF #7 Management 2024"],
  },
  {
    college: "IIM Indore",
    aliases: ["Indian Institute of Management Indore", "IIMI"],
    nirf_rank: 8, nirf_category: "Management",
    city: "Indore", state: "Madhya Pradesh",
    fees_range: "₹20L - 25L", avg_package: 30.1, highest_package: 114.0,
    research_papers: 950, hackathons_won: 4, startups_incubated: 55,
    awards: ["NIRF #8 Management 2024"],
  },
  {
    college: "XLRI Jamshedpur",
    aliases: ["Xavier Labour Relations Institute", "XLRI"],
    nirf_rank: 6, nirf_category: "Management",
    city: "Jamshedpur", state: "Jharkhand",
    fees_range: "₹25L - 28L", avg_package: 32.7, highest_package: 110.0,
    research_papers: 700, hackathons_won: 4, startups_incubated: 50,
    awards: ["NIRF #6 Management 2024", "Best HR & Business School India"],
  },
  {
    college: "FMS Delhi",
    aliases: ["Faculty of Management Studies", "FMS"],
    nirf_rank: 35, nirf_category: "Management",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹2L", avg_package: 34.1, highest_package: 123.0,
    research_papers: 450, awards: ["Best ROI in India", "Top Business School Delhi"],
  },
  {
    college: "SPJIMR Mumbai",
    aliases: ["S.P. Jain Institute of Management and Research"],
    nirf_rank: 20, nirf_category: "Management",
    city: "Mumbai", state: "Maharashtra",
    fees_range: "₹20L - 24L", avg_package: 33.0, highest_package: 77.0,
    research_papers: 600, awards: ["Best Private Business School Mumbai"],
  },
  {
    college: "JBIMS Mumbai",
    aliases: ["Jamnalal Bajaj Institute of Management Studies"],
    nirf_rank: 45, nirf_category: "Management",
    city: "Mumbai", state: "Maharashtra",
    fees_range: "₹6L - 7L", avg_package: 28.0, highest_package: 42.0,
    research_papers: 300, awards: ["CEO Factory of India"],
  },
  {
    college: "IIFT Delhi",
    aliases: ["Indian Institute of Foreign Trade"],
    nirf_rank: 27, nirf_category: "Management",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹18L - 20L", avg_package: 29.1, highest_package: 85.0,
    research_papers: 550, awards: ["Top Trade and International Business School"],
  },
  {
    college: "MDI Gurgaon",
    aliases: ["Management Development Institute"],
    nirf_rank: 13, nirf_category: "Management",
    city: "Gurgaon", state: "Haryana",
    fees_range: "₹22L - 25L", avg_package: 27.6, highest_package: 60.0,
    research_papers: 850, awards: ["NIRF #13 Management 2024"],
  },
  {
    college: "NMIMS Mumbai",
    aliases: ["Narsee Monjee Institute of Management Studies"],
    nirf_rank: 21, nirf_category: "Management",
    city: "Mumbai", state: "Maharashtra",
    fees_range: "₹20L - 24L", avg_package: 26.6, highest_package: 67.0,
    research_papers: 700, awards: ["Top Ranked Private University Mumbai"],
  },
  {
    college: "Symbiosis Pune (SIBM)",
    aliases: ["SIBM Pune", "Symbiosis Institute of Business Management"],
    nirf_rank: 17, nirf_category: "Management",
    city: "Pune", state: "Maharashtra",
    fees_range: "₹22L - 25L", avg_package: 26.7, highest_package: 50.0,
    research_papers: 500, awards: ["Best Private Business School South West India"],
  },

  // ── Design ───────────────────────────────────────────────────────────────────
  {
    college: "NID Ahmedabad",
    aliases: ["National Institute of Design", "NID"],
    nirf_rank: 1, nirf_category: "Design",
    city: "Ahmedabad", state: "Gujarat",
    fees_range: "₹10L - 15L",
    patents: 15, research_papers: 120, hackathons_won: 20, startups_incubated: 35,
    awards: ["NIRF #1 Design 2024", "Best Design Institute India"],
  },
  {
    college: "NIFT Delhi",
    aliases: ["National Institute of Fashion Technology"],
    nirf_rank: 2, nirf_category: "Design",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹12L - 18L",
    patents: 8, research_papers: 80, hackathons_won: 15, startups_incubated: 55,
    awards: ["NIRF #2 Design 2024", "Best Fashion Design Institute Asia"],
  },
  {
    college: "IIT Bombay (Design)",
    aliases: ["IDC IIT Bombay", "Industrial Design Centre"],
    nirf_rank: 3, nirf_category: "Design",
    city: "Mumbai", state: "Maharashtra",
    fees_range: "₹2L - 8L",
    patents: 25, research_papers: 210, awards: ["Top Design Research Institute"],
  },

  // ── Research / Science ───────────────────────────────────────────────────────
  {
    college: "IISc Bangalore",
    aliases: ["Indian Institute of Science", "IISc"],
    nirf_rank: 1, nirf_category: "Research", global_rank: 186,
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹50k - 2L",
    patents: 520, research_papers: 14000, hackathons_won: 15, startups_incubated: 160,
    awards: ["NIRF #1 Research 2024", "QS Top 200 World University", "Best Research University India"],
  },
  {
    college: "TIFR Mumbai",
    aliases: ["Tata Institute of Fundamental Research"],
    nirf_rank: 25, nirf_category: "Research",
    city: "Mumbai", state: "Maharashtra",
    fees_range: "₹0 (Fellowship)",
    research_papers: 5500, awards: ["Premier Fundamental Research Institute"],
  },
  {
    college: "IISER Pune",
    aliases: ["Indian Institute of Science Education and Research"],
    nirf_rank: 35, nirf_category: "Research",
    city: "Pune", state: "Maharashtra",
    fees_range: "₹1L - 3L",
    research_papers: 2800, awards: ["Top Ranked IISER in India"],
  },
  {
    college: "IISER Kolkata",
    aliases: ["Indian Institute of Science Education and Research Kolkata"],
    nirf_rank: 45, nirf_category: "Research",
    city: "Kolkata", state: "West Bengal",
    fees_range: "₹1L - 3L",
    research_papers: 2400, awards: ["Best Research Environment East India"],
  },
  {
    college: "JNCASR Bangalore",
    aliases: ["Jawaharlal Nehru Centre for Advanced Scientific Research"],
    nirf_rank: 10, nirf_category: "Research",
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹0 (Fellowship)",
    research_papers: 3200, awards: ["Top Specialized Research Centre"],
  },
  
  // ── Law ──────────────────────────────────────────────────────────────────────
  {
    college: "NLSIU Bangalore",
    aliases: ["National Law School of India University", "NLS"],
    nirf_rank: 1, nirf_category: "Law",
    city: "Bangalore", state: "Karnataka",
    fees_range: "₹12L - 15L", avg_package: 18.0, highest_package: 32.0,
    awards: ["NIRF #1 Law 2024", "Harvard of the East"],
  },
  {
    college: "NLU Delhi",
    aliases: ["National Law University Delhi"],
    nirf_rank: 2, nirf_category: "Law",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹12L - 15L", avg_package: 17.5, highest_package: 28.0,
    awards: ["NIRF #2 Law 2024"],
  },
  {
    college: "NALSAR Hyderabad",
    aliases: ["NALSAR University of Law"],
    nirf_rank: 3, nirf_category: "Law",
    city: "Hyderabad", state: "Telangana",
    fees_range: "₹12L - 15L", avg_package: 16.5, highest_package: 25.0,
    awards: ["NIRF #3 Law 2024"],
  },
  {
    college: "WBNUJS Kolkata",
    aliases: ["West Bengal National University of Juridical Sciences", "NUJS"],
    nirf_rank: 4, nirf_category: "Law",
    city: "Kolkata", state: "West Bengal",
    fees_range: "₹10L - 14L", avg_package: 15.5, highest_package: 24.0,
    awards: ["NIRF #4 Law 2024"],
  },
  {
    college: "GNLU Gandhinagar",
    aliases: ["Gujarat National Law University"],
    nirf_rank: 7, nirf_category: "Law",
    city: "Gandhinagar", state: "Gujarat",
    fees_range: "₹10L - 14L", avg_package: 14.5,
    awards: ["NIRF #7 Law 2024"],
  },

  // ── Pharmacy ─────────────────────────────────────────────────────────────────
  {
    college: "Jamia Hamdard",
    aliases: ["Jamia Hamdard New Delhi"],
    nirf_rank: 1, nirf_category: "Pharmacy",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹4L - 8L",
    research_papers: 3500, patents: 65, awards: ["NIRF #1 Pharmacy 2024"],
  },
  {
    college: "NIPER Hyderabad",
    aliases: ["National Institute of Pharmaceutical Education and Research"],
    nirf_rank: 2, nirf_category: "Pharmacy",
    city: "Hyderabad", state: "Telangana",
    fees_range: "₹2L - 5L",
    research_papers: 2800, patents: 45, awards: ["NIRF #2 Pharmacy 2024"],
  },
  {
    college: "BITS Pilani (Pharmacy)",
    aliases: [],
    nirf_rank: 3, nirf_category: "Pharmacy",
    city: "Pilani", state: "Rajasthan",
    fees_range: "₹4L - 15L",
    research_papers: 1500, awards: ["Top Private Pharmacy College"],
  },

  // ── Agriculture ──────────────────────────────────────────────────────────────
  {
    college: "ICAR-IARI New Delhi",
    aliases: ["Indian Agricultural Research Institute", "Pusa Institute"],
    nirf_rank: 1, nirf_category: "Agriculture",
    city: "New Delhi", state: "Delhi",
    fees_range: "₹10k - 50k",
    research_papers: 8500, patents: 120, awards: ["NIRF #1 Agriculture 2024"],
  },
  {
    college: "ICAR-NDRI Karnal",
    aliases: ["National Dairy Research Institute"],
    nirf_rank: 2, nirf_category: "Agriculture",
    city: "Karnal", state: "Haryana",
    fees_range: "₹10k - 50k",
    research_papers: 4500, awards: ["Top Dairy Research Institute in World"],
  },
  {
    college: "MANIT Bhopal",
    aliases: ["Maulana Azad National Institute of Technology", "NIT Bhopal"],
    nirf_rank: 65, nirf_category: "Engineering",
    city: "Bhopal", state: "Madhya Pradesh",
    fees_range: "₹1.5L - 6.0L", avg_package: 12.5, highest_package: 52.0,
    patents: 40, research_papers: 1100, hackathons_won: 10, startups_incubated: 25,
    awards: ["Top NIT in Central India"],
  },
  {
    college: "IISER Bhopal",
    aliases: ["Indian Institute of Science Education and Research Bhopal"],
    nirf_rank: 40, nirf_category: "Research",
    city: "Bhopal", state: "Madhya Pradesh",
    fees_range: "₹1L - 3L",
    research_papers: 2200, awards: ["Premier Research Institute in MP"],
  },
];

/**
 * Upsert all college seeds into the college_achievements table.
 * Uses ON CONFLICT DO NOTHING — won't overwrite AI-extracted increments.
 */
export async function seedCollegeAchievements(): Promise<void> {
  const result = await sql`SELECT count(*) as count FROM college_achievements` as any;
  const count = result[0]?.count || 0;
  console.log(`[Achievements Seed] Upserting ${COLLEGE_SEEDS.length} colleges...`);

  for (const seed of COLLEGE_SEEDS) {
    await sql`
      INSERT INTO college_achievements
        (college, aliases, nirf_rank, nirf_category, global_rank,
         patents, research_papers, hackathons_won, startups_incubated, awards,
         city, state, fees_range, avg_package, highest_package, user_rating, total_reviews, logo_url, website)
      VALUES
        (${seed.college}, ${seed.aliases ?? []}, ${seed.nirf_rank ?? null},
         ${seed.nirf_category}, ${seed.global_rank ?? null},
         ${seed.patents ?? 0}, ${seed.research_papers ?? 0}, ${seed.hackathons_won ?? 0},
         ${seed.startups_incubated ?? 0}, ${seed.awards ?? []},
         ${seed.city ?? null}, ${seed.state ?? null}, ${seed.fees_range ?? null},
         ${seed.avg_package ?? 0}, ${seed.highest_package ?? 0},
         ${seed.user_rating ?? 0}, ${seed.total_reviews ?? 0}, ${seed.logo_url ?? null}, ${seed.website ?? null})
      ON CONFLICT (college) DO UPDATE SET
        aliases = EXCLUDED.aliases,
        nirf_rank = EXCLUDED.nirf_rank,
        nirf_category = EXCLUDED.nirf_category,
        global_rank = EXCLUDED.global_rank,
        patents = EXCLUDED.patents,
        research_papers = EXCLUDED.research_papers,
        hackathons_won = EXCLUDED.hackathons_won,
        startups_incubated = EXCLUDED.startups_incubated,
        awards = EXCLUDED.awards,
        city = EXCLUDED.city,
        state = EXCLUDED.state,
        fees_range = EXCLUDED.fees_range,
        avg_package = EXCLUDED.avg_package,
        highest_package = EXCLUDED.highest_package,
        user_rating = EXCLUDED.user_rating,
        total_reviews = EXCLUDED.total_reviews,
        logo_url = EXCLUDED.logo_url,
        website = EXCLUDED.website,
        last_updated = NOW()
    `;
  }

  console.log(`[Achievements Seed] ✅ Seeded ${COLLEGE_SEEDS.length} colleges.`);
}

/**
 * Returns a flat list of all known college canonical names + aliases.
 * Used by the chatbot to detect college mentions in user queries.
 */
export function getKnownColleges(): { canonical: string; aliases: string[] }[] {
  return COLLEGE_SEEDS.map((s) => ({ canonical: s.college, aliases: s.aliases }));
}
